In [ ]:
class review 

hello


In [2]:
class farher():
    def __init__(self,skin,hair_color,eye_color,tall):
        self.skin=skin
        self.hair_color=hair_color
        self.eye_color=eye_color
        self.tall=tall
        
        pass
    def inhertinace (self):
        print(f"my skin is {self.skin} and my eye color is {self.eye_color} and i have {self.hair_color} hair and my tall is {self.tall}")

class son(farher):
    pass 


son1=son("white","black","blue ","1.75 cm ")

son1.inhertinace()


my skin is white and my eye color is blue  and i have black hair and my tall is 1.75 cm 


numpy

In [2]:
import numpy as np
print(np.__version__)

1.26.2


how to create new arrays

In [2]:
my_array=np.array([1,2,2],ndmin=3)
# تقدر تكتب تعدد ال dimantions او تعملهم ب ايدك 
a = np.array([[[1,3,9],[5,6,9]],[[4,5,9],[8,5,3]]])

print(my_array.ndim)
print(a.ndim)

# تقدر ت اكسز علي الي جوا الاري  بكذا بطريقه  والاثنين هيدوا نفس المعني 

print(a[0][0][2])
print(a[0,0,2])

3
3
9
9


In [8]:
# compare data location and the type of data 

list_one=[1,2,"ahmed",10.5] # ال list بتقبل اي نوع ولوجيت تطلب اي اندكس فيها هيقولك علي نوعه 
array_one=np.array([1,2,"ahmed ",10.5]) # هنا هيتعامل معاهم كلهم انهم استرينج 
 
print(type(list_one[0]))
print(type(array_one[0]))

# لوجيت تبص علي المكان المتخزن فيه الاتنين هتلاقيهم مختلفين 
print(id(list_one[0]))
print(id(list_one[-1]))
# لوجيت تبص علي المكان المتخزن فيه الاتنين هتلاقيهم زي بعض عشان دي (array) 
print(id(array_one[0]))
print(id(array_one[-1]))


<class 'int'>
<class 'numpy.str_'>
140705812878120
1561367277968
1561245213648
1561245213648


In [ ]:
#slicing 
a=np.array([["a","q","t"],["a","x","w"],["a","e","r"]])
#print(a[:2:5])
print(a[0:1])# الايندكس الاخير مش بيجيبه 

[]


In [ ]:
# data types and control of array
my_array1=np.array([1,2,3])
my_array2=np.array(["ahmed","x","f"])
my_array3=np.array([1.5,2.69,3.6])

print(my_array1.dtype) #type of data in array 
print(my_array2.dtype)
print(my_array3.dtype)


# create array with spcific data type
my_array4=np.array([1,2,3] , dtype=float) #float ,"float",'f'
my_array5=np.array(["ahmed","x","f"]) # you cant convert srting to any thing else
my_array6=np.array([1.5,2.69,3.6]) 



# change data type of existing array
my_array7=np.array([1,2,3])
my_array7=my_array7.astype(float) # you can convert it to string or bool and to many anothers 
print(my_array7)




int32
<U5
float64
[1. 2. 3.]


In [ ]:
# performane and memory use 

import numpy as np
import time
import sys # عشان نحسب حجم العناصر بلبايت 

elements=15001500

# a = ("John", "Charles", "Mike")
# b = ("Jenny", "Christy", "Monica", "Vicky")
array1=np.arange(elements)
array2 =np.arange(elements)
list1=range(elements)
liss2=range(elements)

list_start=time.time()
list_result=[(n1 +n2) for n1,n2 in zip(array1,array2)] # هياخد 7 ثواني في العمليه دي 
print(f"list time is : {time.time()-list_start}")

array_start=time.time()
array_result=array1+array2 # هياخد جزء من الثانيه 
print(f"array time is : {time.time()-array_start}")



# ravel بتحول الاري الي ون ديمشن 
a = np.array([[[1,3,9],[5,6,9]],[[4,5,9],[8,5,3]]])
print(a.ndim)
z=a.ravel()
print(z.ndim)

list time is : 8.419351816177368
array time is : 0.039009809494018555
3
1


In [15]:
 # array shape and reshape
my_array1=np.array([1,2,3,4])
#print(my_array1.shape) # بيجيب عدد ال elements الي جوا االاري

array_test=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

reshape_array_test=array_test.reshape(5,2,2 ) # انت بتتحكم هنا في شكل وتفصيل الاري
print(reshape_array_test.ndim)
print(reshape_array_test.shape)
print(reshape_array_test)



3
(5, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]
